import {NextIntlClientProvider} from 'next-intl';
import {getMessages, getTranslations, setRequestLocale} from 'next-intl/server';
import {notFound} from 'next/navigation';
import Link from 'next/link';
import type {Metadata} from 'next';
import Logo from '@/components/Logo';
import SiteHeader, {type MegaColumn} from '@/components/SiteHeader';
import {locales} from '@/i18n';
import {categories, countByCategory, type Locale} from '@/lib/catalog';
import {megaHref, megaLinks} from '@/lib/nav';
import {alternatesFor, contact, mailto, offices, siteUrl} from '@/lib/site';
import '../globals.css';
import '../site.css';

/** Branded 1200x630 link-preview card, generated by `npm run build:images`. */
const OG_DEFAULT = '/og-default.png';

type Props = {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
};

export function generateStaticParams() {
  return locales.map((locale) => ({locale}));
}

export async function generateMetadata({params}: Props): Promise<Metadata> {
  const {locale} = await params;
  const isArabic = locale === 'ar';

  return {
    metadataBase: new URL(siteUrl),
    title: {
      default: isArabic
        ? 'LOGX NETWORK | حلول الاتصال والشبكات'
        : 'LOGX NETWORK | Connectivity Solutions',
      template: '%s | LOGX NETWORK'
    },
    description: isArabic
      ? 'كابلات نحاسية CAT6 وCAT6A، أنظمة ألياف بصرية، لوحات توصيل وملحقات بنية الشبكات من LOGX NETWORK.'
      : 'CAT6 and CAT6A copper cabling, fiber optic systems, patch panels and network infrastructure accessories from LOGX NETWORK.',
    alternates: alternatesFor(locale),
    openGraph: {
      siteName: 'LOGX NETWORK',
      type: 'website',
      locale: isArabic ? 'ar' : 'en',
      // Set explicitly rather than through the opengraph-image file convention:
      // the convention's image is dropped once a layout declares its own
      // `openGraph` object. Product pages override this with their own card.
      images: [{url: OG_DEFAULT, width: 1200, height: 630, alt: 'LOGX NETWORK'}]
    },
    twitter: {
      card: 'summary_large_image',
      images: [OG_DEFAULT]
    }
  };
}

export default async function LocaleLayout({children, params}: Props) {
  const {locale} = await params;
  if (!locales.includes(locale as (typeof locales)[number])) notFound();

  // Opts every descendant into static rendering; without it next-intl falls
  // back to rendering each request on demand.
  setRequestLocale(locale);

  const messages = await getMessages();
  const t = await getTranslations();
  const isRTL = locale === 'ar';
  const other: Locale = locale === 'en' ? 'ar' : 'en';

  const language = locale as Locale;
  const sales = offices.find((office) => office.id === 'sa');
  const phone = sales?.phones?.[0] ?? '';

  const links = [
    {href: `/${locale}/datasheets`, label: t('datasheet.index')},
    {href: `/${locale}/company-profile`, label: t('companyProfile.nav')},
    {href: `/${locale}/about`, label: t('nav.about')},
    {href: `/${locale}/contact`, label: t('nav.contact')}
  ];

  const columns: MegaColumn[] = categories.map((category) => ({
    id: category,
    title: t(`categories.${category}`),
    description: t(`catalogueCategories.${category}.desc`),
    count: t('nav.partCount', {count: countByCategory(category)}),
    href: `/${locale}/products?category=${category}`,
    links: megaLinks[category].map((link) => ({
      label: link.label[language],
      href: megaHref(language, category, link)
    }))
  }));

  return (
    <html lang={locale} dir={isRTL ? 'rtl' : 'ltr'}>
      <body className="min-h-screen flex flex-col">
        <NextIntlClientProvider messages={messages}>
          <a className="skip-link" href="#main">
            {t('nav.skip')}
          </a>

          <SiteHeader
            locale={language}
            links={links}
            products={{
              label: t('nav.products'),
              href: `/${locale}/products`,
              allLabel: t('nav.allProducts'),
              columns
            }}
            utility={{
              phone,
              phoneHref: `tel:${phone.replace(/\s+/g, '')}`,
              email: contact.email,
              emailHref: mailto()
            }}
            quote={{label: t('contact.cta'), href: `/${locale}/contact`}}
            language={{
              href: `/${other}`,
              lang: other,
              label: other === 'ar' ? 'العربية' : 'English'
            }}
            labels={{
              primary: t('nav.primary'),
              openMenu: t('nav.openMenu'),
              closeMenu: t('nav.closeMenu'),
              search: t('nav.search'),
              searchPlaceholder: t('nav.searchPlaceholder'),
              searchSubmit: t('nav.searchSubmit'),
              closeSearch: t('nav.closeSearch')
            }}
          />

          <main id="main" className="page-shell">{children}</main>

          <footer className="site-footer">
            <div className="shell">
              <div className="footer-inner">
                <div className="footer-brand">
                  <Logo size="1.5rem" tone="light" />
                  <p>{t('footer.tagline')}</p>
                </div>

                <div className="footer-col">
                  <h3>{t('nav.products')}</h3>
                  <ul>
                    <li>
                      <Link href={`/${locale}/products?category=copper`}>
                        {t('categories.copper')}
                      </Link>
                    </li>
                    <li>
                      <Link href={`/${locale}/products?category=fiber`}>
                        {t('categories.fiber')}
                      </Link>
                    </li>
                    <li>
                      <Link href={`/${locale}/products?category=accessories`}>
                        {t('categories.accessories')}
                      </Link>
                    </li>
                    <li>
                      <Link href={`/${locale}/datasheets`}>{t('datasheet.index')}</Link>
                    </li>
                  </ul>
                </div>

                <div className="footer-col">
                  <h3>{t('nav.contact')}</h3>
                  <ul>
                    <li>
                      <Link href={`/${locale}/contact`}>{t('contact.cta')}</Link>
                    </li>
                    <li>
                      <a href={mailto()}>{contact.email}</a>
                    </li>
                    <li>
                      <Link href={`/${locale}/about`}>{t('nav.about')}</Link>
                    </li>
                    <li>
                      <Link href={`/${locale}/company-profile`}>{t('companyProfile.nav')}</Link>
                    </li>
                  </ul>
                </div>

                <div className="footer-col">
                  <h3>{t('footer.offices')}</h3>
                  <address>
                    {offices.map((office) => (
                      <div className="footer-office" key={office.id}>
                        <strong>{t(`contact.offices.${office.id}.role`)}</strong>
                        <span>{office.name}</span>
                        <span>{office.addressLines.join(', ')}</span>
                      </div>
                    ))}
                  </address>
                </div>
              </div>

              <div className="footer-bar">
                <span>© {new Date().getFullYear()} LOGX NETWORK · {t('footer.disclaimer')}</span>
                <nav aria-label={t('footer.legal')}>
                  <Link href={`/${locale}/privacy`}>{t('footer.privacy')}</Link>
                  <Link href={`/${locale}/terms`}>{t('footer.terms')}</Link>
                </nav>
              </div>
            </div>
          </footer>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
