import {NextIntlClientProvider} from 'next-intl';
import {getMessages, getTranslations, setRequestLocale} from 'next-intl/server';
import {notFound} from 'next/navigation';
import Link from 'next/link';
import type {Metadata} from 'next';
import Logo from '@/components/Logo';
import MobileNav from '@/components/MobileNav';
import {locales} from '@/i18n';
import type {Locale} from '@/lib/catalog';
import {alternatesFor, contact, mailto, offices, siteUrl} from '@/lib/site';
import '../globals.css';

/** Branded 1200x630 link-preview card, generated by `npm run build:images`. */
const OG_DEFAULT = '/og-default.png';

type Props = {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
};

export function generateStaticParams() {
  return locales.map((locale) => ({locale}));
}

export async function generateMetadata({params}: Props): Promise<Metadata> {
  const {locale} = await params;
  const isArabic = locale === 'ar';

  return {
    metadataBase: new URL(siteUrl),
    title: {
      default: isArabic
        ? 'LOGX NETWORK | حلول الاتصال والشبكات'
        : 'LOGX NETWORK | Connectivity Solutions',
      template: '%s | LOGX NETWORK'
    },
    description: isArabic
      ? 'كابلات نحاسية CAT6 وCAT6A، أنظمة ألياف بصرية، لوحات توصيل وملحقات بنية الشبكات من LOGX NETWORK.'
      : 'CAT6 and CAT6A copper cabling, fiber optic systems, patch panels and network infrastructure accessories from LOGX NETWORK.',
    alternates: alternatesFor(locale),
    openGraph: {
      siteName: 'LOGX NETWORK',
      type: 'website',
      locale: isArabic ? 'ar' : 'en',
      // Set explicitly rather than through the opengraph-image file convention:
      // the convention's image is dropped once a layout declares its own
      // `openGraph` object. Product pages override this with their own card.
      images: [{url: OG_DEFAULT, width: 1200, height: 630, alt: 'LOGX NETWORK'}]
    },
    twitter: {
      card: 'summary_large_image',
      images: [OG_DEFAULT]
    }
  };
}

export default async function LocaleLayout({children, params}: Props) {
  const {locale} = await params;
  if (!locales.includes(locale as (typeof locales)[number])) notFound();

  // Opts every descendant into static rendering; without it next-intl falls
  // back to rendering each request on demand.
  setRequestLocale(locale);

  const messages = await getMessages();
  const t = await getTranslations();
  const isRTL = locale === 'ar';
  const other: Locale = locale === 'en' ? 'ar' : 'en';

  const nav = [
    {href: `/${locale}`, label: t('nav.home')},
    {href: `/${locale}/products`, label: t('nav.products')},
    {href: `/${locale}/datasheets`, label: t('datasheet.index')},
    {href: `/${locale}/company-profile`, label: t('companyProfile.nav')},
    {href: `/${locale}/about`, label: t('nav.about')},
    {href: `/${locale}/contact`, label: t('nav.contact')}
  ];

  return (
    <html lang={locale} dir={isRTL ? 'rtl' : 'ltr'}>
      <body className="min-h-screen flex flex-col">
        <NextIntlClientProvider messages={messages}>
          <header className="site-header">
            <div className="shell header-inner">
              <Link href={`/${locale}`} aria-label="LOGX NETWORK">
                <Logo />
              </Link>

              <nav className="main-nav" aria-label={t('nav.primary')}>
                {nav.map((item) => (
                  <Link key={item.href} href={item.href}>
                    {item.label}
                  </Link>
                ))}
              </nav>

              <div className="header-actions">
                <Link href={`/${other}`} className="language-switch flex items-center justify-center" lang={other} hrefLang={other} title={other === 'ar' ? 'عربي' : 'English'}>
                  <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-label={other === 'ar' ? 'عربي' : 'English'}>
                    <circle cx="12" cy="12" r="10"/>
                    <path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"/>
                    <path d="M2 12h20"/>
                  </svg>
                </Link>
                <MobileNav
                  items={nav}
                  langSwitch={{
                    href: `/${other}`,
                    label: (
                      <div className="flex items-center gap-2">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                          <circle cx="12" cy="12" r="10"/>
                          <path d="M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"/>
                          <path d="M2 12h20"/>
                        </svg>
                        <span>{other === 'ar' ? 'عربي' : 'English'}</span>
                      </div>
                    ),
                    lang: other
                  }}
                  menuLabel={t('nav.openMenu')}
                  closeLabel={t('nav.closeMenu')}
                />
              </div>
            </div>
          </header>

          <main className="page-shell">{children}</main>

          <footer className="site-footer">
            <div className="shell">
              <div className="footer-inner">
                <div className="footer-brand">
                  <Logo size="1.5rem" tone="light" />
                  <p>{t('footer.tagline')}</p>
                </div>

                <div className="footer-col">
                  <h3>{t('nav.products')}</h3>
                  <ul>
                    <li>
                      <Link href={`/${locale}/products?category=copper`}>
                        {t('categories.copper')}
                      </Link>
                    </li>
                    <li>
                      <Link href={`/${locale}/products?category=fiber`}>
                        {t('categories.fiber')}
                      </Link>
                    </li>
                    <li>
                      <Link href={`/${locale}/products?category=accessories`}>
                        {t('categories.accessories')}
                      </Link>
                    </li>
                    <li>
                      <Link href={`/${locale}/datasheets`}>{t('datasheet.index')}</Link>
                    </li>
                  </ul>
                </div>

                <div className="footer-col">
                  <h3>{t('nav.contact')}</h3>
                  <ul>
                    <li>
                      <Link href={`/${locale}/contact`}>{t('contact.cta')}</Link>
                    </li>
                    <li>
                      <a href={mailto()}>{contact.email}</a>
                    </li>
                    <li>
                      <Link href={`/${locale}/about`}>{t('nav.about')}</Link>
                    </li>
                    <li>
                      <Link href={`/${locale}/company-profile`}>{t('companyProfile.nav')}</Link>
                    </li>
                  </ul>
                </div>

                <div className="footer-col">
                  <h3>{t('footer.offices')}</h3>
                  <address>
                    {offices.map((office) => (
                      <div className="footer-office" key={office.id}>
                        <strong>{t(`contact.offices.${office.id}.role`)}</strong>
                        <span>{office.name}</span>
                        <span>{office.addressLines.join(', ')}</span>
                      </div>
                    ))}
                  </address>
                </div>
              </div>

              <div className="footer-bar">
                <span>© {new Date().getFullYear()} LOGX NETWORK · {t('footer.disclaimer')}</span>
                <nav aria-label={t('footer.legal')}>
                  <Link href={`/${locale}/privacy`}>{t('footer.privacy')}</Link>
                  <Link href={`/${locale}/terms`}>{t('footer.terms')}</Link>
                </nav>
              </div>
            </div>
          </footer>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
